// 项目全生命周期状态和流程常量定义

// 项目状态枚举
export const PROJECT_STATUS = {
  DRAFT: "DRAFT", // 草稿
  SUBMITTED: "SUBMITTED", // 已提交
  REVIEWING: "REVIEWING", // 审核中
  PRELIMINARY_APPROVED: "PRELIMINARY_APPROVED", // 初审通过
  PRELIMINARY_REJECTED: "PRELIMINARY_REJECTED", // 初审驳回
  EXPERT_REVIEWING: "EXPERT_REVIEWING", // 专家评审中
  APPROVED: "APPROVED", // 立项批准
  REJECTED: "REJECTED", // 已驳回
  TASK_ISSUED: "TASK_ISSUED", // 任务已下发
  TASK_DRAFTING: "TASK_DRAFTING", // 任务书编制中
  TASK_REVIEWING: "TASK_REVIEWING", // 任务书审核中
  TASK_APPROVED: "TASK_APPROVED", // 任务书已批准
  EXECUTING: "EXECUTING", // 执行中
  MIDTERM_CHECKING: "MIDTERM_CHECKING", // 中期检查中
  ANNUAL_CHECKING: "ANNUAL_CHECKING", // 年度检查中
  ACCEPTANCE_APPLYING: "ACCEPTANCE_APPLYING", // 申请验收中
  ACCEPTANCE_REVIEWING: "ACCEPTANCE_REVIEWING", // 验收评审中
  COMPLETED: "COMPLETED", // 已完成
  TERMINATED: "TERMINATED", // 已终止
} as const

export type ProjectStatus = (typeof PROJECT_STATUS)[keyof typeof PROJECT_STATUS]

// 状态中文映射
export const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = {
  [PROJECT_STATUS.DRAFT]: "草稿",
  [PROJECT_STATUS.SUBMITTED]: "已提交",
  [PROJECT_STATUS.REVIEWING]: "审核中",
  [PROJECT_STATUS.PRELIMINARY_APPROVED]: "初审通过",
  [PROJECT_STATUS.PRELIMINARY_REJECTED]: "初审驳回",
  [PROJECT_STATUS.EXPERT_REVIEWING]: "专家评审中",
  [PROJECT_STATUS.APPROVED]: "立项批准",
  [PROJECT_STATUS.REJECTED]: "已驳回",
  [PROJECT_STATUS.TASK_ISSUED]: "任务已下发",
  [PROJECT_STATUS.TASK_DRAFTING]: "任务书编制中",
  [PROJECT_STATUS.TASK_REVIEWING]: "任务书审核中",
  [PROJECT_STATUS.TASK_APPROVED]: "任务书已批准",
  [PROJECT_STATUS.EXECUTING]: "执行中",
  [PROJECT_STATUS.MIDTERM_CHECKING]: "中期检查中",
  [PROJECT_STATUS.ANNUAL_CHECKING]: "年度检查中",
  [PROJECT_STATUS.ACCEPTANCE_APPLYING]: "申请验收中",
  [PROJECT_STATUS.ACCEPTANCE_REVIEWING]: "验收评审中",
  [PROJECT_STATUS.COMPLETED]: "已完成",
  [PROJECT_STATUS.TERMINATED]: "已终止",
}

// 状态颜色映射
export const PROJECT_STATUS_COLORS: Record<ProjectStatus, string> = {
  [PROJECT_STATUS.DRAFT]: "gray",
  [PROJECT_STATUS.SUBMITTED]: "blue",
  [PROJECT_STATUS.REVIEWING]: "blue",
  [PROJECT_STATUS.PRELIMINARY_APPROVED]: "green",
  [PROJECT_STATUS.PRELIMINARY_REJECTED]: "red",
  [PROJECT_STATUS.EXPERT_REVIEWING]: "purple",
  [PROJECT_STATUS.APPROVED]: "green",
  [PROJECT_STATUS.REJECTED]: "red",
  [PROJECT_STATUS.TASK_ISSUED]: "cyan",
  [PROJECT_STATUS.TASK_DRAFTING]: "blue",
  [PROJECT_STATUS.TASK_REVIEWING]: "blue",
  [PROJECT_STATUS.TASK_APPROVED]: "green",
  [PROJECT_STATUS.EXECUTING]: "yellow",
  [PROJECT_STATUS.MIDTERM_CHECKING]: "orange",
  [PROJECT_STATUS.ANNUAL_CHECKING]: "orange",
  [PROJECT_STATUS.ACCEPTANCE_APPLYING]: "purple",
  [PROJECT_STATUS.ACCEPTANCE_REVIEWING]: "purple",
  [PROJECT_STATUS.COMPLETED]: "green",
  [PROJECT_STATUS.TERMINATED]: "gray",
}

// 流程阶段定义
export const WORKFLOW_STAGES = {
  APPLICATION: "APPLICATION", // 申报阶段
  PRELIMINARY_REVIEW: "PRELIMINARY_REVIEW", // 初审阶段
  EXPERT_REVIEW: "EXPERT_REVIEW", // 专家评审阶段
  TASK_ISSUING: "TASK_ISSUING", // 任务下发阶段
  TASK_BOOK: "TASK_BOOK", // 任务书阶段
  EXECUTION: "EXECUTION", // 执行阶段
  MIDTERM: "MIDTERM", // 中期检查阶段
  ANNUAL: "ANNUAL", // 年度检查阶段
  ACCEPTANCE: "ACCEPTANCE", // 验收阶段
  COMPLETED: "COMPLETED", // 完成阶段
} as const

export type WorkflowStage = (typeof WORKFLOW_STAGES)[keyof typeof WORKFLOW_STAGES]

// 流程阶段描述
export const WORKFLOW_STAGE_LABELS: Record<WorkflowStage, string> = {
  [WORKFLOW_STAGES.APPLICATION]: "项目申报",
  [WORKFLOW_STAGES.PRELIMINARY_REVIEW]: "初审",
  [WORKFLOW_STAGES.EXPERT_REVIEW]: "专家评审",
  [WORKFLOW_STAGES.TASK_ISSUING]: "任务下发",
  [WORKFLOW_STAGES.TASK_BOOK]: "任务书编制",
  [WORKFLOW_STAGES.EXECUTION]: "项目执行",
  [WORKFLOW_STAGES.MIDTERM]: "中期检查",
  [WORKFLOW_STAGES.ANNUAL]: "年度检查",
  [WORKFLOW_STAGES.ACCEPTANCE]: "项目验收",
  [WORKFLOW_STAGES.COMPLETED]: "项目完成",
}

// 状态允许的操作映射
export const STATUS_ALLOWED_ACTIONS: Record<ProjectStatus, string[]> = {
  [PROJECT_STATUS.DRAFT]: ["edit", "submit", "delete"],
  [PROJECT_STATUS.SUBMITTED]: ["view", "withdraw"],
  [PROJECT_STATUS.REVIEWING]: ["view"],
  [PROJECT_STATUS.PRELIMINARY_APPROVED]: ["view", "drawExperts"],
  [PROJECT_STATUS.PRELIMINARY_REJECTED]: ["view", "edit", "resubmit"],
  [PROJECT_STATUS.EXPERT_REVIEWING]: ["view"],
  [PROJECT_STATUS.APPROVED]: ["view", "issueTask"],
  [PROJECT_STATUS.REJECTED]: ["view", "edit", "resubmit"],
  [PROJECT_STATUS.TASK_ISSUED]: ["view", "draftTaskBook"],
  [PROJECT_STATUS.TASK_DRAFTING]: ["view", "editTaskBook", "submitTaskBook"],
  [PROJECT_STATUS.TASK_REVIEWING]: ["view"],
  [PROJECT_STATUS.TASK_APPROVED]: ["view", "startExecution"],
  [PROJECT_STATUS.EXECUTING]: ["view", "reportProgress", "submitMidterm", "submitAnnual", "applyAcceptance"],
  [PROJECT_STATUS.MIDTERM_CHECKING]: ["view"],
  [PROJECT_STATUS.ANNUAL_CHECKING]: ["view"],
  [PROJECT_STATUS.ACCEPTANCE_APPLYING]: ["view"],
  [PROJECT_STATUS.ACCEPTANCE_REVIEWING]: ["view"],
  [PROJECT_STATUS.COMPLETED]: ["view", "archive"],
  [PROJECT_STATUS.TERMINATED]: ["view"],
}

// 状态流转规则（当前状态 -> 可流转到的状态列表）
export const STATUS_TRANSITIONS: Record<ProjectStatus, ProjectStatus[]> = {
  [PROJECT_STATUS.DRAFT]: [PROJECT_STATUS.SUBMITTED],
  [PROJECT_STATUS.SUBMITTED]: [PROJECT_STATUS.REVIEWING, PROJECT_STATUS.DRAFT],
  [PROJECT_STATUS.REVIEWING]: [PROJECT_STATUS.PRELIMINARY_APPROVED, PROJECT_STATUS.PRELIMINARY_REJECTED],
  [PROJECT_STATUS.PRELIMINARY_APPROVED]: [PROJECT_STATUS.EXPERT_REVIEWING],
  [PROJECT_STATUS.PRELIMINARY_REJECTED]: [PROJECT_STATUS.DRAFT],
  [PROJECT_STATUS.EXPERT_REVIEWING]: [PROJECT_STATUS.APPROVED, PROJECT_STATUS.REJECTED],
  [PROJECT_STATUS.APPROVED]: [PROJECT_STATUS.TASK_ISSUED],
  [PROJECT_STATUS.REJECTED]: [PROJECT_STATUS.DRAFT],
  [PROJECT_STATUS.TASK_ISSUED]: [PROJECT_STATUS.TASK_DRAFTING],
  [PROJECT_STATUS.TASK_DRAFTING]: [PROJECT_STATUS.TASK_REVIEWING],
  [PROJECT_STATUS.TASK_REVIEWING]: [PROJECT_STATUS.TASK_APPROVED, PROJECT_STATUS.TASK_DRAFTING],
  [PROJECT_STATUS.TASK_APPROVED]: [PROJECT_STATUS.EXECUTING],
  [PROJECT_STATUS.EXECUTING]: [
    PROJECT_STATUS.MIDTERM_CHECKING,
    PROJECT_STATUS.ANNUAL_CHECKING,
    PROJECT_STATUS.ACCEPTANCE_APPLYING,
    PROJECT_STATUS.TERMINATED,
  ],
  [PROJECT_STATUS.MIDTERM_CHECKING]: [PROJECT_STATUS.EXECUTING],
  [PROJECT_STATUS.ANNUAL_CHECKING]: [PROJECT_STATUS.EXECUTING],
  [PROJECT_STATUS.ACCEPTANCE_APPLYING]: [PROJECT_STATUS.ACCEPTANCE_REVIEWING],
  [PROJECT_STATUS.ACCEPTANCE_REVIEWING]: [PROJECT_STATUS.COMPLETED, PROJECT_STATUS.EXECUTING],
  [PROJECT_STATUS.COMPLETED]: [],
  [PROJECT_STATUS.TERMINATED]: [],
}

// 获取当前状态对应的工作流阶段
export function getWorkflowStage(status: ProjectStatus): WorkflowStage {
  const stageMap: Record<ProjectStatus, WorkflowStage> = {
    [PROJECT_STATUS.DRAFT]: WORKFLOW_STAGES.APPLICATION,
    [PROJECT_STATUS.SUBMITTED]: WORKFLOW_STAGES.APPLICATION,
    [PROJECT_STATUS.REVIEWING]: WORKFLOW_STAGES.PRELIMINARY_REVIEW,
    [PROJECT_STATUS.PRELIMINARY_APPROVED]: WORKFLOW_STAGES.PRELIMINARY_REVIEW,
    [PROJECT_STATUS.PRELIMINARY_REJECTED]: WORKFLOW_STAGES.PRELIMINARY_REVIEW,
    [PROJECT_STATUS.EXPERT_REVIEWING]: WORKFLOW_STAGES.EXPERT_REVIEW,
    [PROJECT_STATUS.APPROVED]: WORKFLOW_STAGES.EXPERT_REVIEW,
    [PROJECT_STATUS.REJECTED]: WORKFLOW_STAGES.EXPERT_REVIEW,
    [PROJECT_STATUS.TASK_ISSUED]: WORKFLOW_STAGES.TASK_ISSUING,
    [PROJECT_STATUS.TASK_DRAFTING]: WORKFLOW_STAGES.TASK_BOOK,
    [PROJECT_STATUS.TASK_REVIEWING]: WORKFLOW_STAGES.TASK_BOOK,
    [PROJECT_STATUS.TASK_APPROVED]: WORKFLOW_STAGES.TASK_BOOK,
    [PROJECT_STATUS.EXECUTING]: WORKFLOW_STAGES.EXECUTION,
    [PROJECT_STATUS.MIDTERM_CHECKING]: WORKFLOW_STAGES.MIDTERM,
    [PROJECT_STATUS.ANNUAL_CHECKING]: WORKFLOW_STAGES.ANNUAL,
    [PROJECT_STATUS.ACCEPTANCE_APPLYING]: WORKFLOW_STAGES.ACCEPTANCE,
    [PROJECT_STATUS.ACCEPTANCE_REVIEWING]: WORKFLOW_STAGES.ACCEPTANCE,
    [PROJECT_STATUS.COMPLETED]: WORKFLOW_STAGES.COMPLETED,
    [PROJECT_STATUS.TERMINATED]: WORKFLOW_STAGES.COMPLETED,
  }

  return stageMap[status] || WORKFLOW_STAGES.APPLICATION
}

// 检查状态是否可以流转
export function canTransitionTo(currentStatus: ProjectStatus, targetStatus: ProjectStatus): boolean {
  const allowedTransitions = STATUS_TRANSITIONS[currentStatus] || []
  return allowedTransitions.includes(targetStatus)
}

// 获取状态的进度百分比
export function getStatusProgress(status: ProjectStatus): number {
  const progressMap: Record<ProjectStatus, number> = {
    [PROJECT_STATUS.DRAFT]: 5,
    [PROJECT_STATUS.SUBMITTED]: 10,
    [PROJECT_STATUS.REVIEWING]: 15,
    [PROJECT_STATUS.PRELIMINARY_APPROVED]: 20,
    [PROJECT_STATUS.PRELIMINARY_REJECTED]: 15,
    [PROJECT_STATUS.EXPERT_REVIEWING]: 30,
    [PROJECT_STATUS.APPROVED]: 40,
    [PROJECT_STATUS.REJECTED]: 20,
    [PROJECT_STATUS.TASK_ISSUED]: 45,
    [PROJECT_STATUS.TASK_DRAFTING]: 50,
    [PROJECT_STATUS.TASK_REVIEWING]: 55,
    [PROJECT_STATUS.TASK_APPROVED]: 60,
    [PROJECT_STATUS.EXECUTING]: 70,
    [PROJECT_STATUS.MIDTERM_CHECKING]: 75,
    [PROJECT_STATUS.ANNUAL_CHECKING]: 80,
    [PROJECT_STATUS.ACCEPTANCE_APPLYING]: 85,
    [PROJECT_STATUS.ACCEPTANCE_REVIEWING]: 90,
    [PROJECT_STATUS.COMPLETED]: 100,
    [PROJECT_STATUS.TERMINATED]: 100,
  }

  return progressMap[status] || 0
}
